In [1]:
from dataset import mnist

In [2]:
(x_train, t_train), (x_test, t_test) = mnist.load_mnist(flatten=True, normalize=False)

In [3]:
print(x_train.shape)

(60000, 784)


In [4]:
print(t_train.shape)
print(x_test.shape)
print(t_test.shape)

(60000,)
(10000, 784)
(10000,)


In [5]:
print(t_train)

[5 0 4 ... 5 6 8]


In [6]:
import numpy as np
from PIL import Image


In [7]:
def img_show(img):
    pil_img = Image.fromarray(np.uint8(img))
    pil_img.show()

In [8]:
img_show(x_test[0].reshape(28, 28))

In [9]:
a = np.array([[0.1,2,3],[4,0.5,6],[7,0.8,0.9]])

In [10]:
a

array([[0.1, 2. , 3. ],
       [4. , 0.5, 6. ],
       [7. , 0.8, 0.9]])

In [11]:
np.argmax(a, axis=1)

array([2, 2, 0], dtype=int64)

In [ ]:
def numerical_gradient(f, x):
    h = 1e-4
    grad = np.zeros_like(x)

    for idx in range(x.size):
        tmp_val = x[idx]
        x[idx] = tmp_val + h
        fxh1 = f(x)

        x[idx] = tmp_val - h
        fxh2 = f(x)

        grad

In [ ]:
def gradient_descent(f, init_x, lr=0.01, step_num=100):
    x = init_x

    for i in range(step_num):
        grad = numerical_gradient(f, x)
        x -= lr * grad

    return x